<?php
$body_class;
Am_Di::getInstance()->plugins_protect->get('wordpress')
    ->startLayout($this, isset($meta_title) ? $meta_title : $title, true, empty($body_class) ? null : $body_class);
ob_start();
get_header();
echo str_replace(' style="margin-top: -105px"', '', ob_get_clean());
?>
    <div class="edgtf-container edgtf-default-page-template">
        <div class="edgtf-container-inner clearfix">
            <?php
            include __DIR__ . "/../amember.php";
            ?>
        </div>
    </div>
<?php
get_footer();