<div class="am-helpdesk-reply-panel">
    <div class="am-helpdesk-reply-panel-tools">
        <?php if ($strategy->canUseSnippets()): ?>
        <div class="am-helpdesk-reply-panel-tool am-helpdesk-reply-panel-tool-snippets">
            <a class="local" href="javascript:;"><?php __e('Snippets') ?></a>
        </div>
        <?php endif; ?>
        <?php if ($strategy->canUseFaq()): ?>
        <div class="am-helpdesk-reply-panel-tool am-helpdesk-reply-panel-tool-faq">
            <a class="local" href="javascript:;"><?php __e('FAQ') ?></a>
        </div>
        <?php endif; ?>
        <?php if ($strategy->canUseMarkdown()): ?>
        <div class="am-helpdesk-reply-panel-tool am-helpdesk-reply-panel-tool-markdown">
            <a class="local" href="javascript:;"><?php __e('Markdown') ?></a>
        </div>
        <?php endif; ?>
        <div class="am-helpdesk-reply-panel-tool am-helpdesk-reply-panel-tool-emoji">
            <span class="am-helpdesk-reply-panel-tool-emoji-item" title="+1">👍</span>
            <span class="am-helpdesk-reply-panel-tool-emoji-item" title="-1">👎</span>
            <span class="am-helpdesk-reply-panel-tool-emoji-item" title="Well Done">👏</span>
            <span class="am-helpdesk-reply-panel-tool-emoji-item" title="Agree">🤝</span>
            <span class="am-helpdesk-reply-panel-tool-emoji-item" title="Happy">😀</span>
            <span class="am-helpdesk-reply-panel-tool-emoji-item" title="Confused">🤔</span>
            <span class="am-helpdesk-reply-panel-tool-emoji-item" title="Frustrated">😡</span>
        </div>
    </div>
    <div class="am-helpdesk-reply-panel-content"></div>
</div>